CREATE TABLE POSITION(
    POSITION_ID INT PRIMARY KEY,
    POSITION_NAME VARCHAR(50)
);

CREATE TABLE DEPARTMENT(
    DEPARTMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100)
);

INSERT INTO POSITION (POSITION_ID, POSITION_NAME)
VALUES(1,'平社員');

INSERT INTO DEPARTMENT (DEPARTMENT_NAME)
VALUES('人事部');

CREATE TABLE EMPLOYEE(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PASS VARCHAR(64) NOT NULL,
    MAIL VARCHAR(100) NOT NULL UNIQUE,
    POSITION_ID INT DEFAULT 1,
    DEPARTMENT_ID INT DEFAULT 1,
    PHOTO_PATH NVARCHAR(500),
    ENTER DATE,
    INTRO VARCHAR(200),
    MANAGEMENT BIT NOT NULL DEFAULT 0,
    REMAIN_PAIDHOLIDAY INT
    CONSTRAINT FK_EMPLOYEE_POSITION
        FOREIGN KEY (POSITION_ID)
        REFERENCES POSITION(POSITION_ID),

    CONSTRAINT FK_EMPLOYEE_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE FORZEVENTS (
    event_id INT IDENTITY(1,1) PRIMARY KEY,
    employee_id INT NOT NULL,
    title NVARCHAR(200) NOT NULL,
    content NVARCHAR(MAX),
    area NVARCHAR(100),
    event_date DATE NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_events_employee
        FOREIGN KEY (employee_id)
        REFERENCES EMPLOYEE(id)
);

CREATE TABLE EVENT_COMMENTS (
    comment_id INT IDENTITY(1,1) PRIMARY KEY,
    event_id INT NOT NULL,
    employee_id INT NOT NULL,
    comment NVARCHAR(500) NOT NULL,
    created_at DATETIME DEFAULT GETDATE()
);

CREATE TABLE FORZEVENTSLIKE (
    like_id INT IDENTITY(1,1) PRIMARY KEY,
    employee_id INT NOT NULL,
    event_id INT NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_likes_employee
        FOREIGN KEY (employee_id)
        REFERENCES EMPLOYEE(ID),

    CONSTRAINT FK_likes_event
        FOREIGN KEY (event_id)
        REFERENCES FORZEVENTS(event_id),

    CONSTRAINT U_like UNIQUE (employee_id, event_id)
);

CREATE TABLE FORZDAILYREPORTS (
    daily_report_id INT IDENTITY(1,1) PRIMARY KEY,
    employee_id INT NOT NULL,
    report_type NVARCHAR(20) NOT NULL,
    title NVARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
 
    CONSTRAINT FK_daily_reports_users
        FOREIGN KEY (employee_id)
        REFERENCES EMPLOYEE(ID)
);
 
 
CREATE TABLE FORZDAILYREPORTLIKE (
    like_id INT IDENTITY(1,1) PRIMARY KEY,
    employee_id INT NOT NULL,
    daily_report_id INT NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
 
    CONSTRAINT FK_likes_user
        FOREIGN KEY (employee_id)
        REFERENCES EMPLOYEE(ID),
 
    CONSTRAINT FK_likes_report
        FOREIGN KEY (daily_report_id)
        REFERENCES FORZDAILYREPORTS(daily_report_id),
 
    CONSTRAINT UQ_like UNIQUE (employee_id, daily_report_id)
);
 
 
CREATE TABLE FORZDAILYREPORTCOMMENT (
    comment_id INT IDENTITY(1,1) PRIMARY KEY,
    daily_report_id INT NOT NULL,
    employee_id INT NOT NULL,
    comment_text TEXT NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),
 
    CONSTRAINT FK_comment_report
        FOREIGN KEY (daily_report_id)
        REFERENCES FORZDAILYREPORTS(daily_report_id),
 
    CONSTRAINT FK_comment_user
        FOREIGN KEY (employee_id)
        REFERENCES EMPLOYEE(ID)
);

CREATE TABLE FORZMEDIA(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT,
    MEDIA_TYPE VARCHAR(50),
    TITLE VARCHAR(50),
    CONTENT VARCHAR(200),
    MEDIA_DATE VARCHAR(20),
    created_at DATETIME DEFAULT GETDATE(),
    DEPARTMENT_ID INT
);

CREATE TABLE FORZMEDIALIKES (
    LIKE_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT NOT NULL,
    FORZMEDIA_ID INT NOT NULL,
    created_at DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_FORZMEDIALIKES_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(ID),

    CONSTRAINT FK_FORZMEDIALIKES_FORZMEDIA
        FOREIGN KEY (FORZMEDIA_ID)
        REFERENCES FORZMEDIA(ID)
);

create table MEDIACOMMENT(
	COMMENTID INT IDENTITY(1,1) PRIMARY KEY,
	ID INT,
	NAME VARCHAR(50) NOT NULL,
	COMMENT NVARCHAR(MAX) NOT NULL
);

CREATE TABLE SALARY(
    SALARY_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT,
    AMOUNT INT,
    SALARY_MONTH INT
);

CREATE TABLE EXPENSES(
    EXPENSES_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT,
    AMOUNT INT,
    DETAIL VARCHAR(100),
    APPROVAL VARCHAR(10)
);

CREATE TABLE PAIDHOLIDAY(
    PAIDHOLIDAY_ID INT IDENTITY(1,1) PRIMARY KEY,
    EMPLOYEE_ID INT NOT NULL,
    USED_DAYS DECIMAL(4,1) NOT NULL DEFAULT 0,
    STARTDATE DATE NOT NULL,
    FINISHDATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT '申請中',
    HOLIDAY_TYPE VARCHAR(10),

    CONSTRAINT FK_PAIDHOLIDAY_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(ID)
);

CREATE TABLE QUESTIONNAIRE(
    QUESTION_ID INT,
    EMPLOYEE_ID INT,
    CONTENT TEXT NOT NULL,
    
    CONSTRAINT FK_QUESTIONNAIRE_EMPLOYEE
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(ID)
);

CREATE TABLE CHAT(
    CHAT_ID INT IDENTITY(1,1) PRIMARY KEY,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    MESSAGE NVARCHAR(MAX),
    SEND_TIME DATETIME DEFAULT GETDATE()
);
CREATE TABLE CHAT_GROUP (
    GROUP_ID INT IDENTITY(1,1) PRIMARY KEY,
    GROUP_NAME NVARCHAR(100) NOT NULL,
    CREATED_BY INT NOT NULL,
    CREATED_AT DATETIME DEFAULT GETDATE()
 
);
 
CREATE TABLE GROUP_CHAT (
    CHAT_ID INT IDENTITY(1,1) PRIMARY KEY,
    GROUP_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    MESSAGE NVARCHAR(MAX),
    SEND_TIME DATETIME DEFAULT GETDATE()
);